server:
  port: 9001


spring:
  application:
    name: banking-management-app

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/javatpoint
    password: root

  jpa:
    hibernate:
      ddl-auto: update
